/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels;

import com.motorph.payrollsystem.gui.managementpanels.tools.InformationEditor;
import com.motorph.payrollsystem.access.AccessPolicy;
import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.gui.managementpanels.tools.PayslipViewer;
import com.motorph.payrollsystem.gui.managementpanels.tools.ReportsPanel;
import com.motorph.payrollsystem.gui.managementpanels.tools.SalaryEditor;
import com.motorph.payrollsystem.model.employee.Employee;
import com.motorph.payrollsystem.service.EmployeeService;
import com.motorph.payrollsystem.utility.Dates;
import com.motorph.payrollsystem.utility.FontsAndFormats;
import com.motorph.payrollsystem.utility.ThemeColor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author djjus
 */
public class PayrollReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form EIMPanels
     * 
     * @param appContext use to get employee contexts
     */
    public PayrollReportsPanel(
            AppContext appContext,
            javax.swing.JDialog dialog) {
        this.appContext = appContext;
        this.dialog = dialog;
        this.employeeList = new ArrayList<>();
        this.displayedEmployees = new ArrayList<>();
        this.isIDSelected = true;
        
        
        initComponents();
        reportBox.add(new ReportsPanel(appContext, dialog));
        reportBox.revalidate();
        reportBox.repaint();

    }

    

    private void openInfoDialog(String title, PayslipViewer payslipViewer) {
        payslipViewerDialog.setTitle(title);
        payslipViewerDialog.setContentPane(payslipViewer);
        payslipViewerDialog.pack();
        payslipViewerDialog.setResizable(false);
        payslipViewerDialog.setLocationRelativeTo(null);
        
        payslipViewerDialog.setVisible(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGroup = new javax.swing.ButtonGroup();
        payslipViewerDialog = new javax.swing.JDialog(this.dialog, true);
        headerLabel = new javax.swing.JLabel();
        generateLabel = new javax.swing.JLabel();
        generateBox = new javax.swing.JPanel();
        payrollPeriodComboBox = new javax.swing.JComboBox<>();
        payrollPeriodLabel = new javax.swing.JLabel();
        payrollPeriodBtn = new javax.swing.JButton();
        reportBox = new javax.swing.JPanel();
        reportLabel = new javax.swing.JLabel();

        payslipViewerDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        payslipViewerDialog.setAlwaysOnTop(true);
        payslipViewerDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                payslipViewerDialogWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                payslipViewerDialogWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout payslipViewerDialogLayout = new javax.swing.GroupLayout(payslipViewerDialog.getContentPane());
        payslipViewerDialog.getContentPane().setLayout(payslipViewerDialogLayout);
        payslipViewerDialogLayout.setHorizontalGroup(
            payslipViewerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        payslipViewerDialogLayout.setVerticalGroup(
            payslipViewerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        headerLabel.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        headerLabel.setText("Payroll Report Tools");

        generateLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        generateLabel.setText("Generate Payroll Report");

        generateBox.setBackground(new java.awt.Color(255, 255, 255));
        generateBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        payrollPeriodComboBox.setBackground(new java.awt.Color(255, 255, 255));
        payrollPeriodComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        payrollPeriodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan 01, 2020 - Jan 15,2020" }));

        payrollPeriodLabel.setBackground(new java.awt.Color(255, 255, 255));
        payrollPeriodLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        payrollPeriodLabel.setText("Payroll Period");

        payrollPeriodBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        payrollPeriodBtn.setText("Generate Report");

        javax.swing.GroupLayout generateBoxLayout = new javax.swing.GroupLayout(generateBox);
        generateBox.setLayout(generateBoxLayout);
        generateBoxLayout.setHorizontalGroup(
            generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payrollPeriodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payrollPeriodComboBox, 0, 220, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(payrollPeriodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        generateBoxLayout.setVerticalGroup(
            generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBoxLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(payrollPeriodLabel)
                .addGap(0, 0, 0)
                .addGroup(generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payrollPeriodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payrollPeriodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        reportBox.setBackground(new java.awt.Color(255, 255, 255));
        reportBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        reportBox.setLayout(new java.awt.BorderLayout());

        reportLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        reportLabel.setText("Payroll Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportLabel)
                    .addComponent(generateBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateLabel)
                    .addComponent(headerLabel)
                    .addComponent(reportBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerLabel)
                .addGap(18, 18, 18)
                .addComponent(generateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(reportLabel)
                .addGap(6, 6, 6)
                .addComponent(reportBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payslipViewerDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_payslipViewerDialogWindowClosing
        // TODO add your handling code here:
        payslipViewerDialog.dispose();
    }//GEN-LAST:event_payslipViewerDialogWindowClosing

    private void payslipViewerDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_payslipViewerDialogWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_payslipViewerDialogWindowClosed

    private javax.swing.JDialog dialog;
    private boolean isIDSelected;
    private List<Employee> employeeList;
    private List<Employee> displayedEmployees;
    private AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel generateBox;
    private javax.swing.JLabel generateLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton payrollPeriodBtn;
    private javax.swing.JComboBox<String> payrollPeriodComboBox;
    private javax.swing.JLabel payrollPeriodLabel;
    private javax.swing.JDialog payslipViewerDialog;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JPanel reportBox;
    private javax.swing.JLabel reportLabel;
    // End of variables declaration//GEN-END:variables
}
