/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels;

import com.motorph.payrollsystem.gui.managementpanels.tools.InformationEditor;
import com.motorph.payrollsystem.access.AccessPolicy;
import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.gui.managementpanels.tools.PayslipViewer;
import com.motorph.payrollsystem.gui.managementpanels.tools.ReportsPanel;
import com.motorph.payrollsystem.gui.managementpanels.tools.SalaryEditor;
import com.motorph.payrollsystem.model.employee.Employee;
import com.motorph.payrollsystem.model.payslip.PayrollPeriod;
import com.motorph.payrollsystem.service.EmployeeService;
import com.motorph.payrollsystem.utility.Dates;
import com.motorph.payrollsystem.utility.FontsAndFormats;
import com.motorph.payrollsystem.utility.ThemeColor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author djjus
 */
public class PayrollReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form EIMPanels
     * 
     * @param appContext use to get employee contexts
     */
    public PayrollReportsPanel(
            AppContext appContext,
            javax.swing.JDialog dialog) {
        this.appContext = appContext;
        this.parentDialog = dialog;

        initComponents();
        loadPayrollPeriods();
        initReportsPanel();
        

    }
    
    private void loadPayrollPeriods() {
        payrollPeriodComboBox.removeAllItems();
        
        try {
            List<PayrollPeriod> periods = appContext
                    .getPayrollReportService()
                    .getAllAvailablePayrollPeriods();
            
            if (periods == null || periods.isEmpty()) {
                payrollPeriodComboBox.setEnabled(false);
                return;
            }
            
            for (PayrollPeriod period : periods) {
                payrollPeriodComboBox.addItem(period);
            }
            
            payrollPeriodComboBox.setEnabled(true);
            payrollPeriodComboBox.setSelectedIndex(0);
            
            
        } catch (IllegalStateException | IllegalArgumentException ex) {
            payrollPeriodComboBox.setEnabled(false);
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Payroll Period Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
        } catch (Exception ex) {
            payrollPeriodComboBox.setEnabled(false);
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed to load payroll periods.",
                    "Payroll Period Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
        
    }
    
    private void initReportsPanel() {
        reportBox.add(new ReportsPanel(appContext, parentDialog));
        reportBox.revalidate();
        reportBox.repaint();
    }
    
    private void handleExistingPeriod(PayrollPeriod period) {
        
    }
    

    

    private void openInfoDialog(String title, PayslipViewer payslipViewer) {
        otherDialog.setTitle(title);
        otherDialog.setContentPane(payslipViewer);
        otherDialog.pack();
        otherDialog.setResizable(false);
        otherDialog.setLocationRelativeTo(null);
        
        otherDialog.setVisible(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGroup = new javax.swing.ButtonGroup();
        otherDialog = new javax.swing.JDialog(this.parentDialog, true);
        generatingDialog = new javax.swing.JDialog(this.parentDialog, true);
        existingReportDialog = new javax.swing.JDialog(this.parentDialog, true);
        existingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        headerLabel = new javax.swing.JLabel();
        generateLabel = new javax.swing.JLabel();
        generateBox = new javax.swing.JPanel();
        payrollPeriodComboBox = new javax.swing.JComboBox<>();
        payrollPeriodLabel = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        reportBox = new javax.swing.JPanel();
        reportLabel = new javax.swing.JLabel();

        otherDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        otherDialog.setAlwaysOnTop(true);
        otherDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                otherDialogWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                otherDialogWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout otherDialogLayout = new javax.swing.GroupLayout(otherDialog.getContentPane());
        otherDialog.getContentPane().setLayout(otherDialogLayout);
        otherDialogLayout.setHorizontalGroup(
            otherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        otherDialogLayout.setVerticalGroup(
            otherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        generatingDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        generatingDialog.setAlwaysOnTop(true);
        generatingDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                generatingDialogWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                generatingDialogWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout generatingDialogLayout = new javax.swing.GroupLayout(generatingDialog.getContentPane());
        generatingDialog.getContentPane().setLayout(generatingDialogLayout);
        generatingDialogLayout.setHorizontalGroup(
            generatingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        generatingDialogLayout.setVerticalGroup(
            generatingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        existingReportDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        existingReportDialog.setAlwaysOnTop(true);
        existingReportDialog.setBackground(new java.awt.Color(255, 255, 255));

        existingPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setText("The payroll report for this period already exists.");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Do you want to view it instead?");

        jButton1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton1.setText("View Report");
        jButton1.setFocusPainted(false);

        jButton2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton2.setText("Regenerate Report");
        jButton2.setFocusPainted(false);

        jButton3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setFocusPainted(false);

        javax.swing.GroupLayout existingPanelLayout = new javax.swing.GroupLayout(existingPanel);
        existingPanel.setLayout(existingPanelLayout);
        existingPanelLayout.setHorizontalGroup(
            existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );
        existingPanelLayout.setVerticalGroup(
            existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout existingReportDialogLayout = new javax.swing.GroupLayout(existingReportDialog.getContentPane());
        existingReportDialog.getContentPane().setLayout(existingReportDialogLayout);
        existingReportDialogLayout.setHorizontalGroup(
            existingReportDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(existingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        existingReportDialogLayout.setVerticalGroup(
            existingReportDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(existingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        headerLabel.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        headerLabel.setText("Payroll Report Tools");

        generateLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        generateLabel.setText("Generate Payroll Report");

        generateBox.setBackground(new java.awt.Color(255, 255, 255));
        generateBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        payrollPeriodComboBox.setBackground(new java.awt.Color(255, 255, 255));
        payrollPeriodComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        payrollPeriodLabel.setBackground(new java.awt.Color(255, 255, 255));
        payrollPeriodLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        payrollPeriodLabel.setText("Payroll Period");

        generateBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        generateBtn.setText("Generate Report");
        generateBtn.addActionListener(this::generateBtnActionPerformed);

        javax.swing.GroupLayout generateBoxLayout = new javax.swing.GroupLayout(generateBox);
        generateBox.setLayout(generateBoxLayout);
        generateBoxLayout.setHorizontalGroup(
            generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payrollPeriodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(payrollPeriodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        generateBoxLayout.setVerticalGroup(
            generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBoxLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(payrollPeriodLabel)
                .addGap(0, 0, 0)
                .addGroup(generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payrollPeriodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        reportBox.setBackground(new java.awt.Color(255, 255, 255));
        reportBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        reportBox.setLayout(new java.awt.BorderLayout());

        reportLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        reportLabel.setText("Existing Payroll Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportLabel)
                    .addComponent(generateBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateLabel)
                    .addComponent(headerLabel)
                    .addComponent(reportBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerLabel)
                .addGap(18, 18, 18)
                .addComponent(generateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(reportLabel)
                .addGap(6, 6, 6)
                .addComponent(reportBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void otherDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_otherDialogWindowClosing
        // TODO add your handling code here:
        otherDialog.dispose();
    }//GEN-LAST:event_otherDialogWindowClosing

    private void otherDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_otherDialogWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherDialogWindowClosed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
        PayrollPeriod period = (PayrollPeriod) payrollPeriodComboBox.getSelectedItem();
        if (period == null) {
            generateBtn.setEnabled(false);
            //open error dialog
            return;
        }

        try {
            if (appContext.getPayrollReportService().hasExistingReport(period)) {
                handleExistingPeriod(period);
            } else {
                //generate
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed to open report folder.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_generateBtnActionPerformed

    private void generatingDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_generatingDialogWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_generatingDialogWindowClosed

    private void generatingDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_generatingDialogWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_generatingDialogWindowClosing

    private javax.swing.JDialog parentDialog;
    private AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel existingPanel;
    private javax.swing.JDialog existingReportDialog;
    private javax.swing.JPanel generateBox;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel generateLabel;
    private javax.swing.JDialog generatingDialog;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDialog otherDialog;
    private javax.swing.JComboBox<PayrollPeriod> payrollPeriodComboBox;
    private javax.swing.JLabel payrollPeriodLabel;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JPanel reportBox;
    private javax.swing.JLabel reportLabel;
    // End of variables declaration//GEN-END:variables
}
