/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels;

import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.gui.managementpanels.tools.PayslipViewer;
import com.motorph.payrollsystem.gui.managementpanels.tools.ReportsPanel;
import com.motorph.payrollsystem.gui.managementpanels.tools.reportviewermodal.MainReportViewer;
import com.motorph.payrollsystem.model.payslip.PayrollPeriod;
import com.motorph.payrollsystem.model.report.PayrollReport;
import java.util.List;

/**
 *
 * @author djjus
 */
public class PayrollReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form EIMPanels
     * 
     * @param appContext use to get employee contexts
     */
    public PayrollReportsPanel(
            AppContext appContext,
            javax.swing.JDialog dialog) {
        this.appContext = appContext;
        this.parentDialog = dialog;
        this.selectedPeriod = null;

        initComponents();
        loadPayrollPeriods();
        loadReportsPanel();
        

    }
    
    private void loadPayrollPeriods() {
        payrollPeriodComboBox.removeAllItems();
        
        try {
            List<PayrollPeriod> periods = appContext
                    .getPayrollReportService()
                    .getAllAvailablePayrollPeriods();
            
            if (periods == null || periods.isEmpty()) {
                payrollPeriodComboBox.setEnabled(false);
                generateBtn.setEnabled(false);
                return;
            }
            
            for (PayrollPeriod period : periods) {
                payrollPeriodComboBox.addItem(period);
            }
            
            payrollPeriodComboBox.setEnabled(true);
            payrollPeriodComboBox.setSelectedIndex(0);
            generateBtn.setEnabled(true);
            
            
        } catch (IllegalStateException | IllegalArgumentException ex) {
            payrollPeriodComboBox.setEnabled(false);
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Payroll Period Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
        } catch (Exception ex) {
            payrollPeriodComboBox.setEnabled(false);
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed to load payroll periods.",
                    "Payroll Period Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
        
    }
    
    private void loadReportsPanel() {
        reportBox.removeAll();
        reportBox.add(new ReportsPanel(appContext, parentDialog));
        reportBox.revalidate();
        reportBox.repaint();
    }
    
    private void handleGeneration() {

        try {
            generateBtn.setEnabled(false);
            String currentUserName = appContext.getSessionManager().getCurrentEmployee().getLastNameInitial();
            PayrollReport report = appContext
                    .getPayrollReportService()
                    .generatePayrollReport(selectedPeriod, currentUserName);
            
            generateBtn.setEnabled(true);
            
            reportViewerDialog.setContentPane(new MainReportViewer(report, reportViewerDialog));
            dialogOpener("Payroll Report Viewer", reportViewerDialog);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed create payroll report",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
    }
    
    private void dialogOpener(String title, javax.swing.JDialog dialog) {
        dialog.setTitle(title);
        dialog.pack();
        dialog.setResizable(false);
        dialog.setLocationRelativeTo(null);
        
        dialog.setVisible(true);
    }

    

    private void openInfoDialog(String title, PayslipViewer payslipViewer) {
        otherDialog.setTitle(title);
        otherDialog.setContentPane(payslipViewer);
        otherDialog.pack();
        otherDialog.setResizable(false);
        otherDialog.setLocationRelativeTo(null);
        
        otherDialog.setVisible(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGroup = new javax.swing.ButtonGroup();
        otherDialog = new javax.swing.JDialog(this.parentDialog, true);
        existingReportDialog = new javax.swing.JDialog(this.parentDialog, true);
        existingPanel = new javax.swing.JPanel();
        existingLabel1 = new javax.swing.JLabel();
        existingLabel2 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        regenerateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        reportViewerDialog = new javax.swing.JDialog(this.parentDialog, true);
        headerLabel = new javax.swing.JLabel();
        generateLabel = new javax.swing.JLabel();
        generateBox = new javax.swing.JPanel();
        payrollPeriodComboBox = new javax.swing.JComboBox<>();
        payrollPeriodLabel = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        reportBox = new javax.swing.JPanel();
        reportLabel = new javax.swing.JLabel();

        otherDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        otherDialog.setAlwaysOnTop(true);
        otherDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                otherDialogWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                otherDialogWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout otherDialogLayout = new javax.swing.GroupLayout(otherDialog.getContentPane());
        otherDialog.getContentPane().setLayout(otherDialogLayout);
        otherDialogLayout.setHorizontalGroup(
            otherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        otherDialogLayout.setVerticalGroup(
            otherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        existingReportDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        existingReportDialog.setAlwaysOnTop(true);
        existingReportDialog.setBackground(new java.awt.Color(255, 255, 255));

        existingPanel.setBackground(new java.awt.Color(255, 255, 255));

        existingLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        existingLabel1.setText("The payroll report for this period already exists.");

        existingLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        existingLabel2.setText("Do you want to view it instead?");

        viewBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        viewBtn.setText("View Report");
        viewBtn.setFocusPainted(false);
        viewBtn.addActionListener(this::viewBtnActionPerformed);

        regenerateBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        regenerateBtn.setText("Regenerate Report");
        regenerateBtn.setFocusPainted(false);
        regenerateBtn.addActionListener(this::regenerateBtnActionPerformed);

        cancelBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setFocusPainted(false);
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        javax.swing.GroupLayout existingPanelLayout = new javax.swing.GroupLayout(existingPanel);
        existingPanel.setLayout(existingPanelLayout);
        existingPanelLayout.setHorizontalGroup(
            existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(existingLabel1)
                    .addComponent(existingLabel2))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, existingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regenerateBtn)
                .addGap(12, 12, 12)
                .addComponent(cancelBtn)
                .addGap(24, 24, 24))
        );
        existingPanelLayout.setVerticalGroup(
            existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existingPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(existingLabel1)
                .addGap(12, 12, 12)
                .addComponent(existingLabel2)
                .addGap(18, 18, 18)
                .addGroup(existingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBtn)
                    .addComponent(regenerateBtn)
                    .addComponent(cancelBtn))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout existingReportDialogLayout = new javax.swing.GroupLayout(existingReportDialog.getContentPane());
        existingReportDialog.getContentPane().setLayout(existingReportDialogLayout);
        existingReportDialogLayout.setHorizontalGroup(
            existingReportDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(existingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        existingReportDialogLayout.setVerticalGroup(
            existingReportDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(existingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        reportViewerDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        reportViewerDialog.setAlwaysOnTop(true);
        reportViewerDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                reportViewerDialogWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                reportViewerDialogWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout reportViewerDialogLayout = new javax.swing.GroupLayout(reportViewerDialog.getContentPane());
        reportViewerDialog.getContentPane().setLayout(reportViewerDialogLayout);
        reportViewerDialogLayout.setHorizontalGroup(
            reportViewerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        reportViewerDialogLayout.setVerticalGroup(
            reportViewerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        headerLabel.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        headerLabel.setText("Payroll Report Tools");

        generateLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        generateLabel.setText("Generate Payroll Report");

        generateBox.setBackground(new java.awt.Color(255, 255, 255));
        generateBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        payrollPeriodComboBox.setBackground(new java.awt.Color(255, 255, 255));
        payrollPeriodComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        payrollPeriodComboBox.addActionListener(this::payrollPeriodComboBoxActionPerformed);

        payrollPeriodLabel.setBackground(new java.awt.Color(255, 255, 255));
        payrollPeriodLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        payrollPeriodLabel.setText("Payroll Period");

        generateBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        generateBtn.setText("Generate Report");
        generateBtn.addActionListener(this::generateBtnActionPerformed);

        javax.swing.GroupLayout generateBoxLayout = new javax.swing.GroupLayout(generateBox);
        generateBox.setLayout(generateBoxLayout);
        generateBoxLayout.setHorizontalGroup(
            generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payrollPeriodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(payrollPeriodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        generateBoxLayout.setVerticalGroup(
            generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBoxLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(payrollPeriodLabel)
                .addGap(0, 0, 0)
                .addGroup(generateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payrollPeriodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        reportBox.setBackground(new java.awt.Color(255, 255, 255));
        reportBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        reportBox.setLayout(new java.awt.BorderLayout());

        reportLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        reportLabel.setText("Existing Payroll Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportLabel)
                    .addComponent(generateBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateLabel)
                    .addComponent(headerLabel)
                    .addComponent(reportBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerLabel)
                .addGap(18, 18, 18)
                .addComponent(generateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(reportLabel)
                .addGap(6, 6, 6)
                .addComponent(reportBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void otherDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_otherDialogWindowClosing
        // TODO add your handling code here:
        otherDialog.dispose();
    }//GEN-LAST:event_otherDialogWindowClosing

    private void otherDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_otherDialogWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherDialogWindowClosed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
        if (selectedPeriod == null) {
            generateBtn.setEnabled(false);
            //open error dialog
            return;
        }

        try {
            if (appContext.getPayrollReportService().hasExistingReport(selectedPeriod)) {
                String title = "Existing Report";
                dialogOpener(title, existingReportDialog);
            } else {
                //generate
                handleGeneration();
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed to open report folder.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_generateBtnActionPerformed

    private void payrollPeriodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollPeriodComboBoxActionPerformed
        // TODO add your handling code here:
        this.selectedPeriod = (PayrollPeriod) payrollPeriodComboBox.getSelectedItem();
        generateBtn.setEnabled(true);
    }//GEN-LAST:event_payrollPeriodComboBoxActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        existingReportDialog.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void regenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regenerateBtnActionPerformed
        // TODO add your handling code here:
        existingReportDialog.dispose();
        handleGeneration();
    }//GEN-LAST:event_regenerateBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        //view report dialog
        existingReportDialog.dispose();
        
        try {
            generateBtn.setEnabled(false);
            PayrollReport report = appContext
                    .getPayrollReportService().loadPayrollReport(selectedPeriod);
            generateBtn.setEnabled(true);
            
            reportViewerDialog.setContentPane(new MainReportViewer(report, reportViewerDialog));
            dialogOpener("Payroll Report Viewer", reportViewerDialog);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed create payroll report",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void reportViewerDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_reportViewerDialogWindowClosed
        // TODO add your handling code here:
        loadReportsPanel();
    }//GEN-LAST:event_reportViewerDialogWindowClosed

    private void reportViewerDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_reportViewerDialogWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_reportViewerDialogWindowClosing

    private javax.swing.JDialog parentDialog;
    private AppContext appContext;
    private PayrollPeriod selectedPeriod;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel existingLabel1;
    private javax.swing.JLabel existingLabel2;
    private javax.swing.JPanel existingPanel;
    private javax.swing.JDialog existingReportDialog;
    private javax.swing.JPanel generateBox;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel generateLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JDialog otherDialog;
    private javax.swing.JComboBox<PayrollPeriod> payrollPeriodComboBox;
    private javax.swing.JLabel payrollPeriodLabel;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JButton regenerateBtn;
    private javax.swing.JPanel reportBox;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JDialog reportViewerDialog;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
