/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels;

import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.model.employee.Employee;

/**
 *
 * @author djjus
 */
public class ReviewLeavePanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewLeavePanel
     */
    public ReviewLeavePanel(
            AppContext appContext,
            javax.swing.JDialog parentDialog
    ) {
        this.appContext = appContext;
        this.currentEmployee = appContext.getSessionManager().getCurrentEmployee();
        this.parentDialog = parentDialog;
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        headerLabel.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        headerLabel.setText("LEAVE REQUEST MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(headerLabel)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addContainerGap(583, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private AppContext appContext;
    private Employee currentEmployee;
    private javax.swing.JDialog parentDialog;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    // End of variables declaration//GEN-END:variables
}
