/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.GUI.rightsidepanels;

import com.motorph.payrollsystem.app.AppContext;
import com.motorph.payrollsystem.app.SessionManager;
import com.motorph.payrollsystem.utility.Dates;
import java.time.LocalDateTime;

/**
 *
 * @author djjus
 */
public class EmployeeInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     * @param appContext the current logged in user/employee
     */
    public EmployeeInfoPanel(AppContext appContext) {
        this.appContext = appContext;
        initComponents();
        
        SessionManager currSession = appContext.getSessionManager();
        LocalDateTime loginTime = currSession.getLoginTime();
        
        employeeNoText.setText(currSession.getCurrentEmployee().getFullName());
        loggedInTimeLabel.setText(Dates.formattedTime(loginTime));
        
        String dateLabelStr = Dates.dayOfWeek(loginTime) + 
                ", " + 
                Dates.fullDate(loginTime);
        dateLabel.setText(dateLabelStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        employeeNoLabel = new javax.swing.JLabel();
        employeeNoText = new javax.swing.JLabel();
        preTimeLabel = new javax.swing.JLabel();
        loggedInTimeLabel = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        decorLine = new javax.swing.JPanel();
        loggedInTimeLabel1 = new javax.swing.JLabel();
        loggedInTimeLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 640));

        dateLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        dateLabel.setText("Last Name :");

        employeeNoLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        employeeNoLabel.setText("Employee No :");

        employeeNoText.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        employeeNoText.setText("00000");

        preTimeLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        preTimeLabel.setText("First Name :");

        loggedInTimeLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        loggedInTimeLabel.setText("Birthday :");

        dashboardLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        dashboardLabel.setText("EMPLOYEE INFORMATION");

        decorLine.setBackground(new java.awt.Color(240, 240, 240));
        decorLine.setDoubleBuffered(false);

        javax.swing.GroupLayout decorLineLayout = new javax.swing.GroupLayout(decorLine);
        decorLine.setLayout(decorLineLayout);
        decorLineLayout.setHorizontalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        decorLineLayout.setVerticalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        loggedInTimeLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        loggedInTimeLabel1.setText("Address :");

        loggedInTimeLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        loggedInTimeLabel2.setText("Phone Number : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(dashboardLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(preTimeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(loggedInTimeLabel)
                            .addComponent(loggedInTimeLabel1)
                            .addComponent(loggedInTimeLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(dashboardLabel)
                .addGap(6, 6, 6)
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNoLabel)
                    .addComponent(employeeNoText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loggedInTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loggedInTimeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loggedInTimeLabel2)
                .addContainerGap(403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel decorLine;
    private javax.swing.JLabel employeeNoLabel;
    private javax.swing.JLabel employeeNoText;
    private javax.swing.JLabel loggedInTimeLabel;
    private javax.swing.JLabel loggedInTimeLabel1;
    private javax.swing.JLabel loggedInTimeLabel2;
    private javax.swing.JLabel preTimeLabel;
    // End of variables declaration//GEN-END:variables
}
