/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.GUI.rightsidepanels;

import com.motorph.payrollsystem.app.AppContext;
import com.motorph.payrollsystem.app.SessionManager;
import com.motorph.payrollsystem.utility.Dates;
import java.time.LocalDateTime;

/**
 *
 * @author djjus
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     * @param appContext the current logged in user/employee
     */
    public HomePanel(AppContext appContext) {
        this.appContext = appContext;
        initComponents();
        
        SessionManager currSession = appContext.getSessionManager();
        LocalDateTime loginTime = currSession.getLoginTime();
        
        nameLabel.setText(currSession.getCurrentEmployee().getFullName());
        loggedInTimeLabel.setText(Dates.formattedTime(loginTime));
        
        String dateLabelStr = Dates.dayOfWeek(loginTime) + 
                ", " + 
                Dates.fullDate(loginTime);
        dateLabel.setText(dateLabelStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        preTimeLabel = new javax.swing.JLabel();
        loggedInTimeLabel = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 640));

        dateLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dateLabel.setText("Wednesday, January 1, 1972");

        welcomeLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        welcomeLabel.setText("Welcome back,");

        nameLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        nameLabel.setText("John Doe");

        preTimeLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        preTimeLabel.setText("You logged in at:");

        loggedInTimeLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loggedInTimeLabel.setText("00:00 AM");

        dashboardLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        dashboardLabel.setText("DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(preTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loggedInTimeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(welcomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dashboardLabel))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(dashboardLabel)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preTimeLabel)
                    .addComponent(loggedInTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addContainerGap(485, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel loggedInTimeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel preTimeLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
