/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.GUI.rightsidepanels;

import com.motorph.payrollsystem.access.AccessPolicy;
import com.motorph.payrollsystem.app.AppContext;
import com.motorph.payrollsystem.app.SessionManager;
import com.motorph.payrollsystem.utility.Dates;
import com.motorph.payrollsystem.utility.ThemeColor;
import java.time.LocalDateTime;

/**
 *
 * @author djjus
 */
public class ManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     * @param appContext the current logged in user/employee
     */
    public ManagementPanel(AppContext appContext) {
        this.appContext = appContext;
        initComponents();
        applyAccessControl();


        

    }
    
    public void applyAccessControl() {
        AccessPolicy policy = appContext.getSessionManager().getAccessPolicy();

        manageCard(reviewLeaveCard, policy.canReviewLeaveRequests());
        manageCard(eimCard, policy.canManageEmployees());
        manageCard(runPayrollCard, policy.canRunPayroll());
        manageCard(viewPayrollCard, policy.canViewPayrollReports());
        
        layoutManager.revalidate();
        layoutManager.repaint();
        
        
    }
    
    private void manageCard(javax.swing.JPanel panel, boolean can) {
        panel.setVisible(can);
        panel.setEnabled(can);
    }
    
    private void cardMouseEntered(javax.swing.JPanel card) {
        card.setBackground(ThemeColor.hoverIn());
        
    };
    
    private void cardMouseExited(javax.swing.JPanel card) {
        card.setBackground(ThemeColor.hoverOut());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managementLabel = new javax.swing.JLabel();
        decorLine = new javax.swing.JPanel();
        layoutManager = new javax.swing.JPanel();
        eimCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reviewLeaveCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        runPayrollCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        viewPayrollCard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 640));

        managementLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        managementLabel.setText("MANAGEMENT");

        decorLine.setBackground(new java.awt.Color(240, 240, 240));
        decorLine.setDoubleBuffered(false);

        javax.swing.GroupLayout decorLineLayout = new javax.swing.GroupLayout(decorLine);
        decorLine.setLayout(decorLineLayout);
        decorLineLayout.setHorizontalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        decorLineLayout.setVerticalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        layoutManager.setBackground(new java.awt.Color(255, 255, 255));
        layoutManager.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 30));

        eimCard.setBackground(new java.awt.Color(255, 255, 255));
        eimCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        eimCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eimCard.setPreferredSize(new java.awt.Dimension(280, 200));
        eimCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eimCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eimCardMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPLOYEE INFORMATION MANAGEMENT");

        javax.swing.GroupLayout eimCardLayout = new javax.swing.GroupLayout(eimCard);
        eimCard.setLayout(eimCardLayout);
        eimCardLayout.setHorizontalGroup(
            eimCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        eimCardLayout.setVerticalGroup(
            eimCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eimCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        layoutManager.add(eimCard);

        reviewLeaveCard.setBackground(new java.awt.Color(255, 255, 255));
        reviewLeaveCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        reviewLeaveCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reviewLeaveCard.setPreferredSize(new java.awt.Dimension(280, 200));
        reviewLeaveCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reviewLeaveCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reviewLeaveCardMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REVIEW LEAVE REQUEST");

        javax.swing.GroupLayout reviewLeaveCardLayout = new javax.swing.GroupLayout(reviewLeaveCard);
        reviewLeaveCard.setLayout(reviewLeaveCardLayout);
        reviewLeaveCardLayout.setHorizontalGroup(
            reviewLeaveCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        reviewLeaveCardLayout.setVerticalGroup(
            reviewLeaveCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reviewLeaveCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        layoutManager.add(reviewLeaveCard);

        runPayrollCard.setBackground(new java.awt.Color(255, 255, 255));
        runPayrollCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        runPayrollCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        runPayrollCard.setPreferredSize(new java.awt.Dimension(280, 200));
        runPayrollCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                runPayrollCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                runPayrollCardMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RUN PAYROLL");

        javax.swing.GroupLayout runPayrollCardLayout = new javax.swing.GroupLayout(runPayrollCard);
        runPayrollCard.setLayout(runPayrollCardLayout);
        runPayrollCardLayout.setHorizontalGroup(
            runPayrollCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        runPayrollCardLayout.setVerticalGroup(
            runPayrollCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runPayrollCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );

        layoutManager.add(runPayrollCard);

        viewPayrollCard.setBackground(new java.awt.Color(255, 255, 255));
        viewPayrollCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        viewPayrollCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPayrollCard.setPreferredSize(new java.awt.Dimension(280, 200));
        viewPayrollCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPayrollCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPayrollCardMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VIEW PAYROLL REPORTS");

        javax.swing.GroupLayout viewPayrollCardLayout = new javax.swing.GroupLayout(viewPayrollCard);
        viewPayrollCard.setLayout(viewPayrollCardLayout);
        viewPayrollCardLayout.setHorizontalGroup(
            viewPayrollCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        viewPayrollCardLayout.setVerticalGroup(
            viewPayrollCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPayrollCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(24, 24, 24))
        );

        layoutManager.add(viewPayrollCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(managementLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(layoutManager, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(managementLabel)
                .addGap(6, 6, 6)
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(layoutManager, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eimCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eimCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(eimCard);
    }//GEN-LAST:event_eimCardMouseEntered

    private void eimCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eimCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(eimCard);
    }//GEN-LAST:event_eimCardMouseExited

    private void reviewLeaveCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewLeaveCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(reviewLeaveCard);
    }//GEN-LAST:event_reviewLeaveCardMouseEntered

    private void reviewLeaveCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewLeaveCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(reviewLeaveCard);
    }//GEN-LAST:event_reviewLeaveCardMouseExited

    private void runPayrollCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runPayrollCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(runPayrollCard);
    }//GEN-LAST:event_runPayrollCardMouseEntered

    private void runPayrollCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runPayrollCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(runPayrollCard);
    }//GEN-LAST:event_runPayrollCardMouseExited

    private void viewPayrollCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(viewPayrollCard);
    }//GEN-LAST:event_viewPayrollCardMouseEntered

    private void viewPayrollCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(viewPayrollCard);
    }//GEN-LAST:event_viewPayrollCardMouseExited

    private AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel decorLine;
    private javax.swing.JPanel eimCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel layoutManager;
    private javax.swing.JLabel managementLabel;
    private javax.swing.JPanel reviewLeaveCard;
    private javax.swing.JPanel runPayrollCard;
    private javax.swing.JPanel viewPayrollCard;
    // End of variables declaration//GEN-END:variables
}
