/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.rightsidepanels;


import com.motorph.payrollsystem.gui.managementpanels.EIMPanels;
import com.motorph.payrollsystem.access.AccessPolicy;
import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.config.SessionManager;
import com.motorph.payrollsystem.gui.managementpanels.ESMPanel;
import com.motorph.payrollsystem.gui.managementpanels.ReviewLeavePanel;
import com.motorph.payrollsystem.utility.Dates;
import com.motorph.payrollsystem.utility.ThemeColor;
import java.awt.Dimension;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;

/**
 *
 * @author djjus
 */
public class ManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     * @param appContext the current logged in user/employee
     */
    public ManagementPanel(AppContext appContext) {
        this.appContext = appContext;
        this.policy = appContext.getSessionManager().getAccessPolicy();
        this.moduleIcon = new ImageIcon(
                getClass().getResource("/images/tab-icon/motorPhFrame.png")
        );
        
        initComponents();
        applyAccessControl();
    }
    
    
    private void applyAccessControl() {
        manageCard(reviewLeaveCard, policy.canReviewLeaveRequests());
        manageCard(eimCard, policy.canManageEmployees());
        manageCard(updateEmployeeSalaryCard, policy.canUpdateEmployeeSalary());
        manageCard(employeePayrollCard, policy.canViewEmployeePayroll());
        manageCard(payrollReportsCard, policy.canMakePayrollReports());
        manageCard(viewPayrollReportsCard, policy.canViewPayrollReports());
        manageCard(userAccountMngtCard, policy.canManageUserAccount());
        
        layoutManager.revalidate();
        layoutManager.repaint();

    }
    
    private void manageCard(javax.swing.JPanel panel, boolean can) {
        panel.setVisible(can);
        panel.setEnabled(can);
    }
    
    private void cardMouseEntered(javax.swing.JPanel card) {
        card.setBackground(ThemeColor.hoverIn());
        
    };
    
    private void cardMouseExited(javax.swing.JPanel card) {
        card.setBackground(ThemeColor.hoverOut());
    }
    
    private void openNewWindow(
            String title,
            javax.swing.JPanel window,
            java.awt.Dimension dimension) {
        dialog.setContentPane(window);
        dialog.setPreferredSize(dimension);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setResizable(false);
        dialog.setTitle(title);
        
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        managementLabel = new javax.swing.JLabel();
        decorLine = new javax.swing.JPanel();
        layoutManager = new javax.swing.JPanel();
        eimCard = new javax.swing.JPanel();
        eimLabel = new javax.swing.JLabel();
        reviewLeaveCard = new javax.swing.JPanel();
        reviewLeaveLabel = new javax.swing.JLabel();
        updateEmployeeSalaryCard = new javax.swing.JPanel();
        updateEmployeeSalaryLabel = new javax.swing.JLabel();
        employeePayrollCard = new javax.swing.JPanel();
        employeePayrollLabel = new javax.swing.JLabel();
        payrollReportsCard = new javax.swing.JPanel();
        payrollReportsLabel = new javax.swing.JLabel();
        viewPayrollReportsCard = new javax.swing.JPanel();
        viewPayrollReportsLabel = new javax.swing.JLabel();
        userAccountMngtCard = new javax.swing.JPanel();
        userAccountManagementLabel = new javax.swing.JLabel();

        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialog.setAlwaysOnTop(true);
        dialog.setIconImage(moduleIcon.getImage());
        dialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 640));

        managementLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        managementLabel.setText("MANAGEMENT");

        decorLine.setBackground(new java.awt.Color(240, 240, 240));
        decorLine.setDoubleBuffered(false);

        javax.swing.GroupLayout decorLineLayout = new javax.swing.GroupLayout(decorLine);
        decorLine.setLayout(decorLineLayout);
        decorLineLayout.setHorizontalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        decorLineLayout.setVerticalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        layoutManager.setBackground(new java.awt.Color(255, 255, 255));
        layoutManager.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 30));

        eimCard.setBackground(new java.awt.Color(255, 255, 255));
        eimCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        eimCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eimCard.setPreferredSize(new java.awt.Dimension(280, 200));
        eimCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eimCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eimCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eimCardMouseExited(evt);
            }
        });

        eimLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        eimLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eimLabel.setText("EMPLOYEE INFORMATION MANAGEMENT");

        javax.swing.GroupLayout eimCardLayout = new javax.swing.GroupLayout(eimCard);
        eimCard.setLayout(eimCardLayout);
        eimCardLayout.setHorizontalGroup(
            eimCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        eimCardLayout.setVerticalGroup(
            eimCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eimCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(eimLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(eimCard);

        reviewLeaveCard.setBackground(new java.awt.Color(255, 255, 255));
        reviewLeaveCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        reviewLeaveCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reviewLeaveCard.setPreferredSize(new java.awt.Dimension(280, 200));
        reviewLeaveCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewLeaveCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reviewLeaveCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reviewLeaveCardMouseExited(evt);
            }
        });

        reviewLeaveLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        reviewLeaveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviewLeaveLabel.setText("LEAVE REQUESTS");

        javax.swing.GroupLayout reviewLeaveCardLayout = new javax.swing.GroupLayout(reviewLeaveCard);
        reviewLeaveCard.setLayout(reviewLeaveCardLayout);
        reviewLeaveCardLayout.setHorizontalGroup(
            reviewLeaveCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reviewLeaveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        reviewLeaveCardLayout.setVerticalGroup(
            reviewLeaveCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reviewLeaveCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(reviewLeaveLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(reviewLeaveCard);

        updateEmployeeSalaryCard.setBackground(new java.awt.Color(255, 255, 255));
        updateEmployeeSalaryCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        updateEmployeeSalaryCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateEmployeeSalaryCard.setPreferredSize(new java.awt.Dimension(280, 200));
        updateEmployeeSalaryCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateEmployeeSalaryCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateEmployeeSalaryCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateEmployeeSalaryCardMouseExited(evt);
            }
        });

        updateEmployeeSalaryLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        updateEmployeeSalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateEmployeeSalaryLabel.setText("UPDATE EMPLOYEE SALARY");

        javax.swing.GroupLayout updateEmployeeSalaryCardLayout = new javax.swing.GroupLayout(updateEmployeeSalaryCard);
        updateEmployeeSalaryCard.setLayout(updateEmployeeSalaryCardLayout);
        updateEmployeeSalaryCardLayout.setHorizontalGroup(
            updateEmployeeSalaryCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateEmployeeSalaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        updateEmployeeSalaryCardLayout.setVerticalGroup(
            updateEmployeeSalaryCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateEmployeeSalaryCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(updateEmployeeSalaryLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(updateEmployeeSalaryCard);

        employeePayrollCard.setBackground(new java.awt.Color(255, 255, 255));
        employeePayrollCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        employeePayrollCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeePayrollCard.setPreferredSize(new java.awt.Dimension(280, 200));
        employeePayrollCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeePayrollCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeePayrollCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeePayrollCardMouseExited(evt);
            }
        });

        employeePayrollLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        employeePayrollLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeePayrollLabel.setText("EMPLOYEE PAYSLIP VIEWER");

        javax.swing.GroupLayout employeePayrollCardLayout = new javax.swing.GroupLayout(employeePayrollCard);
        employeePayrollCard.setLayout(employeePayrollCardLayout);
        employeePayrollCardLayout.setHorizontalGroup(
            employeePayrollCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeePayrollLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        employeePayrollCardLayout.setVerticalGroup(
            employeePayrollCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePayrollCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(employeePayrollLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(employeePayrollCard);

        payrollReportsCard.setBackground(new java.awt.Color(255, 255, 255));
        payrollReportsCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        payrollReportsCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payrollReportsCard.setPreferredSize(new java.awt.Dimension(280, 200));
        payrollReportsCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payrollReportsCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payrollReportsCardMouseExited(evt);
            }
        });

        payrollReportsLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        payrollReportsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payrollReportsLabel.setText("PAYROLL REPORTS");

        javax.swing.GroupLayout payrollReportsCardLayout = new javax.swing.GroupLayout(payrollReportsCard);
        payrollReportsCard.setLayout(payrollReportsCardLayout);
        payrollReportsCardLayout.setHorizontalGroup(
            payrollReportsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(payrollReportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        payrollReportsCardLayout.setVerticalGroup(
            payrollReportsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payrollReportsCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(payrollReportsLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(payrollReportsCard);

        viewPayrollReportsCard.setBackground(new java.awt.Color(255, 255, 255));
        viewPayrollReportsCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        viewPayrollReportsCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPayrollReportsCard.setPreferredSize(new java.awt.Dimension(280, 200));
        viewPayrollReportsCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPayrollReportsCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPayrollReportsCardMouseExited(evt);
            }
        });

        viewPayrollReportsLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        viewPayrollReportsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewPayrollReportsLabel.setText("VIEW PAYROLL REPORTS");

        javax.swing.GroupLayout viewPayrollReportsCardLayout = new javax.swing.GroupLayout(viewPayrollReportsCard);
        viewPayrollReportsCard.setLayout(viewPayrollReportsCardLayout);
        viewPayrollReportsCardLayout.setHorizontalGroup(
            viewPayrollReportsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewPayrollReportsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        viewPayrollReportsCardLayout.setVerticalGroup(
            viewPayrollReportsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPayrollReportsCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(viewPayrollReportsLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(viewPayrollReportsCard);

        userAccountMngtCard.setBackground(new java.awt.Color(255, 255, 255));
        userAccountMngtCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        userAccountMngtCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userAccountMngtCard.setPreferredSize(new java.awt.Dimension(280, 200));
        userAccountMngtCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userAccountMngtCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userAccountMngtCardMouseExited(evt);
            }
        });

        userAccountManagementLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        userAccountManagementLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userAccountManagementLabel.setText("USER ACCOUNT MANAGEMENT");

        javax.swing.GroupLayout userAccountMngtCardLayout = new javax.swing.GroupLayout(userAccountMngtCard);
        userAccountMngtCard.setLayout(userAccountMngtCardLayout);
        userAccountMngtCardLayout.setHorizontalGroup(
            userAccountMngtCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userAccountManagementLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        userAccountMngtCardLayout.setVerticalGroup(
            userAccountMngtCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userAccountMngtCardLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(userAccountManagementLabel)
                .addGap(24, 24, 24))
        );

        layoutManager.add(userAccountMngtCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(managementLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(layoutManager, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(managementLabel)
                .addGap(6, 6, 6)
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layoutManager, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eimCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eimCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(eimCard);
    }//GEN-LAST:event_eimCardMouseEntered

    private void eimCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eimCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(eimCard);
    }//GEN-LAST:event_eimCardMouseExited

    private void reviewLeaveCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewLeaveCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(reviewLeaveCard);
    }//GEN-LAST:event_reviewLeaveCardMouseEntered

    private void reviewLeaveCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewLeaveCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(reviewLeaveCard);
    }//GEN-LAST:event_reviewLeaveCardMouseExited

    private void updateEmployeeSalaryCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeeSalaryCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(updateEmployeeSalaryCard);
    }//GEN-LAST:event_updateEmployeeSalaryCardMouseEntered

    private void updateEmployeeSalaryCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeeSalaryCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(updateEmployeeSalaryCard);
    }//GEN-LAST:event_updateEmployeeSalaryCardMouseExited

    private void employeePayrollCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePayrollCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(employeePayrollCard);
    }//GEN-LAST:event_employeePayrollCardMouseEntered

    private void employeePayrollCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePayrollCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(employeePayrollCard);
    }//GEN-LAST:event_employeePayrollCardMouseExited

    private void eimCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eimCardMouseClicked
        // TODO add your handling code here:
        //Validate first
        if (policy == null || !policy.canManageEmployees()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Access denied.");
            return;
        }
        
        String title = "Employee Information Management (" + 
                appContext.getSessionManager().getCurrentEmployee().getLastNameInitial() +
                " - " +
                appContext.getSessionManager().getAccessPolicy().roleName() + 
                ")";
        openNewWindow(
                title,
                new EIMPanels(appContext, dialog),
                new Dimension(822, 700)
        );
    }//GEN-LAST:event_eimCardMouseClicked

    private void reviewLeaveCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewLeaveCardMouseClicked
        // TODO add your handling code here:
        if (policy == null || !policy.canReviewLeaveRequests()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Access denied.");
            return;
        }
        
        String title = "Leave Request Management (" + 
                appContext.getSessionManager().getCurrentEmployee().getLastNameInitial() +
                " - " +
                appContext.getSessionManager().getAccessPolicy().roleName() + 
                ")";
        
        openNewWindow(
                title,
                new ReviewLeavePanel(appContext, dialog),
                new Dimension(827, 646)
        );
    }//GEN-LAST:event_reviewLeaveCardMouseClicked

    private void payrollReportsCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollReportsCardMouseEntered
        // TODO add your handling code here:
         cardMouseEntered(payrollReportsCard);
    }//GEN-LAST:event_payrollReportsCardMouseEntered

    private void payrollReportsCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollReportsCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(payrollReportsCard);
    }//GEN-LAST:event_payrollReportsCardMouseExited

    private void viewPayrollReportsCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollReportsCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(viewPayrollReportsCard);
    }//GEN-LAST:event_viewPayrollReportsCardMouseEntered

    private void viewPayrollReportsCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPayrollReportsCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(viewPayrollReportsCard);
    }//GEN-LAST:event_viewPayrollReportsCardMouseExited

    private void userAccountMngtCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccountMngtCardMouseEntered
        // TODO add your handling code here:
        cardMouseEntered(userAccountMngtCard);
    }//GEN-LAST:event_userAccountMngtCardMouseEntered

    private void userAccountMngtCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccountMngtCardMouseExited
        // TODO add your handling code here:
        cardMouseExited(userAccountMngtCard);
    }//GEN-LAST:event_userAccountMngtCardMouseExited

    private void updateEmployeeSalaryCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeeSalaryCardMouseClicked
        // TODO add your handling code here:
        if (policy == null || !policy.canUpdateEmployeeSalary()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Access denied.");
            return;
        }
        
        String title = "Employee Salary Management (" + 
                appContext.getSessionManager().getCurrentEmployee().getLastNameInitial() +
                " - " +
                appContext.getSessionManager().getAccessPolicy().roleName() + 
                ")";
        openNewWindow(
                title,
                new ESMPanel(appContext, dialog),
                new Dimension(822, 700)
        );
    }//GEN-LAST:event_updateEmployeeSalaryCardMouseClicked

    private void employeePayrollCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePayrollCardMouseClicked
        // TODO add your handling code here:
        if (policy == null || !policy.canViewEmployeePayroll()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Access denied.");
            return;
        }
        
        String title = "Employee Payslip Viewer(" + 
                appContext.getSessionManager().getCurrentEmployee().getLastNameInitial() +
                " - " +
                appContext.getSessionManager().getAccessPolicy().roleName() + 
                ")";
        openNewWindow(
                title,
                new ESMPanel(appContext, dialog),
                new Dimension(822, 700)
        );
    }//GEN-LAST:event_employeePayrollCardMouseClicked
    
    private ImageIcon moduleIcon;
    private AccessPolicy policy;
    private AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel decorLine;
    private javax.swing.JDialog dialog;
    private javax.swing.JPanel eimCard;
    private javax.swing.JLabel eimLabel;
    private javax.swing.JPanel employeePayrollCard;
    private javax.swing.JLabel employeePayrollLabel;
    private javax.swing.JPanel layoutManager;
    private javax.swing.JLabel managementLabel;
    private javax.swing.JPanel payrollReportsCard;
    private javax.swing.JLabel payrollReportsLabel;
    private javax.swing.JPanel reviewLeaveCard;
    private javax.swing.JLabel reviewLeaveLabel;
    private javax.swing.JPanel updateEmployeeSalaryCard;
    private javax.swing.JLabel updateEmployeeSalaryLabel;
    private javax.swing.JLabel userAccountManagementLabel;
    private javax.swing.JPanel userAccountMngtCard;
    private javax.swing.JPanel viewPayrollReportsCard;
    private javax.swing.JLabel viewPayrollReportsLabel;
    // End of variables declaration//GEN-END:variables
}
