/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels.tools.useraccountpanel;

import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.model.auth.UserAccount;

/**
 *
 * @author djjus
 */
public class ResetPasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResetPasswordPanel
     */
    public ResetPasswordPanel(
            AppContext appContext,
            UserAccount selectedUser,
            javax.swing.JDialog dialog
    ) {
        this.appContext = appContext;
        this.selectedUser = selectedUser;
        this.parentDialog = dialog;

        initComponents();
        this.defaultEcho = newPasswordField.getEchoChar();
        
        loadDetails();
        hookShowPassword();
    }
    
    private void loadDetails() {
        String employeeNo = selectedUser.getEmployeeNo();
        String selectedName = getEmployeeName(employeeNo);
        
        employeeField.setText(selectedName);
        userNameField.setText(selectedUser.getUsername());
    }
    
    private String getEmployeeName(String employeeNo) {
        try {
            return appContext.getEmployeeService().findByEmployeeNo(employeeNo).getLastFirstName();
        } catch (Exception ex) {
            ex.printStackTrace();
            return "Employee name can't found.";
        }
    }
    
    private void hookShowPassword() {
        showPasswordCheck.addActionListener(e -> {
            if (showPasswordCheck.isSelected()) {
                newPasswordField.setEchoChar((char)0);
                confirmPasswordField.setEchoChar((char)0);
            } else {
                newPasswordField.setEchoChar(defaultEcho);
                confirmPasswordField.setEchoChar(defaultEcho);
            }
        });
    }
    
    private void handleReset(String newPassword) {
        
        try {
            UserAccount account = 
                    appContext
                    .getUserAccountService()
                    .resetPassword(selectedUser.getEmployeeNo(), newPassword);
            //success
            String label = "Password successfully reset";
            showSuccessDialog(label);
            
            parentDialog.dispose();
            
        } catch (Exception ex) {
            //error
            showErrorDialog("Failed to reset. Try again later.");
            ex.printStackTrace();
        }
    }
    
    private void showSuccessDialog(String label) {
        successLabel.setText(label);
        openDialog("Successful", successDialog);
    }
    
    private void showErrorDialog(String label) {
        errorLabel.setText(label);
        openDialog("Error", errorDialog);
    }
    
    private void openDialog(String title, javax.swing.JDialog dialog) {
        
        dialog.setTitle(title);
        dialog.pack();
        dialog.setResizable(false);
        dialog.setLocationRelativeTo(parentDialog);
        
        dialog.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        successDialog = new javax.swing.JDialog(this.parentDialog, true);
        successPanel = new javax.swing.JPanel();
        successLabel = new javax.swing.JLabel();
        successBtn = new javax.swing.JButton();
        errorDialog = new javax.swing.JDialog(this.parentDialog, true);
        errorPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        errorBtn = new javax.swing.JButton();
        resestPasswordPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        employeeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        employeeField = new javax.swing.JLabel();
        userNameField = new javax.swing.JLabel();
        newLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        confirmLabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        cancelBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        showPasswordCheck = new javax.swing.JCheckBox();

        successDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        successPanel.setBackground(new java.awt.Color(255, 255, 255));

        successLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        successLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        successLabel.setText("Password successfully reset");

        successBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        successBtn.setText("Ok");
        successBtn.addActionListener(this::successBtnActionPerformed);

        javax.swing.GroupLayout successPanelLayout = new javax.swing.GroupLayout(successPanel);
        successPanel.setLayout(successPanelLayout);
        successPanelLayout.setHorizontalGroup(
            successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successPanelLayout.createSequentialGroup()
                .addGroup(successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(successPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(successPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(successBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        successPanelLayout.setVerticalGroup(
            successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(successLabel)
                .addGap(18, 18, 18)
                .addComponent(successBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(successPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        successDialogLayout.setVerticalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(successPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        errorPanel.setBackground(new java.awt.Color(255, 255, 255));

        errorLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Failed to reset. Try again.");

        errorBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        errorBtn.setText("Ok");
        errorBtn.addActionListener(this::errorBtnActionPerformed);

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(errorPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(errorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(errorLabel)
                .addGap(18, 18, 18)
                .addComponent(errorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        resestPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        header.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        header.setText("Reset Password");

        employeeLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        employeeLabel.setText("Employee :");

        userNameLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        userNameLabel.setText("Username :");

        employeeField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        employeeField.setText("Don Justine Fontanilla");

        userNameField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        userNameField.setText("Don Justine Fontanilla");

        newLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        newLabel.setText("New Password :");

        newPasswordField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        newPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        confirmLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        confirmLabel.setText("Confirm Password :");

        confirmPasswordField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        cancelBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        resetBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(this::resetBtnActionPerformed);

        showPasswordCheck.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordCheck.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        showPasswordCheck.setText("Show Password");

        javax.swing.GroupLayout resestPasswordPanelLayout = new javax.swing.GroupLayout(resestPasswordPanel);
        resestPasswordPanel.setLayout(resestPasswordPanelLayout);
        resestPasswordPanelLayout.setHorizontalGroup(
            resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                        .addComponent(header)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(confirmPasswordField)
                            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showPasswordCheck)
                                    .addComponent(confirmLabel)
                                    .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(newLabel)
                                        .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                            .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(employeeLabel)
                                                .addComponent(userNameLabel))
                                            .addGap(12, 12, 12)
                                            .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(employeeField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(newPasswordField)))
                                .addGap(0, 5, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        resestPasswordPanelLayout.setVerticalGroup(
            resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(header)
                .addGap(12, 12, 12)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeLabel)
                    .addComponent(employeeField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameField)
                    .addComponent(userNameLabel))
                .addGap(11, 11, 11)
                .addComponent(newLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(confirmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(showPasswordCheck)
                .addGap(12, 12, 12)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resestPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resestPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        parentDialog.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        String newPassword = new String(newPasswordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());
        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
            showErrorDialog("Password fields are required.");
            return;
        }
        
        if (newPassword.length() < 5) {
            showErrorDialog("Password should have length of 5 and above.");
            return;
        }
        
        if(!newPassword.equals(confirmPassword)) {
            showErrorDialog("Passwords do not match.");
            return;
        }
        
        handleReset(newPassword);
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void successBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_successBtnActionPerformed
        // TODO add your handling code here:
        successDialog.dispose();
    }//GEN-LAST:event_successBtnActionPerformed

    private void errorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorBtnActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
    }//GEN-LAST:event_errorBtnActionPerformed

    private char defaultEcho;
    private AppContext appContext;
    private UserAccount selectedUser;
    private javax.swing.JDialog parentDialog;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel employeeField;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JButton errorBtn;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel newLabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPanel resestPasswordPanel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JCheckBox showPasswordCheck;
    private javax.swing.JButton successBtn;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel successPanel;
    private javax.swing.JLabel userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
