/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels.tools.useraccountpanel;

import com.motorph.payrollsystem.config.AppContext;
import com.motorph.payrollsystem.model.auth.UserAccount;

/**
 *
 * @author djjus
 */
public class StatusChangePanel extends javax.swing.JPanel {

    /**
     * Creates new form ResetPasswordPanel
     */
    public StatusChangePanel(
            AppContext appContext,
            UserAccount selectedUser,
            javax.swing.JDialog dialog
    ) {
        this.appContext = appContext;
        this.selectedUser = selectedUser;
        this.parentDialog = dialog;

        initComponents();
        
        loadDetails();
    }
    
    private void loadDetails() {
        String employeeNo = selectedUser.getEmployeeNo();
        String selectedName = getEmployeeName(employeeNo);
        String from = selectedUser.isActive() ? "ACTIVE" : "INACTIVE";
        String to = !selectedUser.isActive() ? "ACTIVE" : "INACTIVE";
        
        employeeField.setText(selectedName);
        userNameField.setText(selectedUser.getUsername());
        currentStatusLabel.setText(from);
        changeToLabel.setText(to);
        
    }
    
    private String getEmployeeName(String employeeNo) {
        try {
            return appContext.getEmployeeService().findByEmployeeNo(employeeNo).getLastFirstName();
        } catch (Exception ex) {
            ex.printStackTrace();
            return "Employee name can't found.";
        }
    }
    
    
    private void handleStatusChange() {
        
        try {
            UserAccount account = 
                    appContext
                    .getUserAccountService()
                    .setAccountActive(selectedUser.getEmployeeNo(), !selectedUser.isActive());
            
            //success
            String label = "Staus successfully changed.";
            parentDialog.dispose();
            showSuccessDialog(label);
            
        } catch (IllegalStateException ex) {
            showErrorDialog(ex.getMessage());
        } catch (Exception ex) {
            showErrorDialog("An unexpected error occurred.");
            ex.printStackTrace();
        }
    }
    
    private void showSuccessDialog(String label) {
        successLabel.setText(label);
        openDialog("Successful", successDialog);
    }
    
    private void showErrorDialog(String label) {
        errorLabel.setText(label);
        openDialog("Error", errorDialog);
    }
    
    private void openDialog(String title, javax.swing.JDialog dialog) {
        
        dialog.setTitle(title);
        dialog.pack();
        dialog.setResizable(false);
        dialog.setLocationRelativeTo(parentDialog);
        
        dialog.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        successDialog = new javax.swing.JDialog(this.parentDialog, true);
        successPanel = new javax.swing.JPanel();
        successLabel = new javax.swing.JLabel();
        successBtn = new javax.swing.JButton();
        errorDialog = new javax.swing.JDialog(this.parentDialog, true);
        errorPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        errorBtn = new javax.swing.JButton();
        resestPasswordPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        employeeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        employeeField = new javax.swing.JLabel();
        userNameField = new javax.swing.JLabel();
        currentStatus = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        decorLine = new javax.swing.JPanel();
        currentStatusLabel = new javax.swing.JLabel();
        changeToStatus = new javax.swing.JLabel();
        changeToLabel = new javax.swing.JLabel();

        successDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        successPanel.setBackground(new java.awt.Color(255, 255, 255));

        successLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        successLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        successLabel.setText("Password successfully reset");

        successBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        successBtn.setText("Ok");
        successBtn.addActionListener(this::successBtnActionPerformed);

        javax.swing.GroupLayout successPanelLayout = new javax.swing.GroupLayout(successPanel);
        successPanel.setLayout(successPanelLayout);
        successPanelLayout.setHorizontalGroup(
            successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successPanelLayout.createSequentialGroup()
                .addGroup(successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(successPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(successPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(successBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        successPanelLayout.setVerticalGroup(
            successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(successLabel)
                .addGap(18, 18, 18)
                .addComponent(successBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(successPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        successDialogLayout.setVerticalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(successPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        errorPanel.setBackground(new java.awt.Color(255, 255, 255));

        errorLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Username must be at least 8 characters long.");

        errorBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        errorBtn.setText("Ok");
        errorBtn.addActionListener(this::errorBtnActionPerformed);

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorPanelLayout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorPanelLayout.createSequentialGroup()
                        .addComponent(errorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(errorLabel)
                .addGap(18, 18, 18)
                .addComponent(errorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        resestPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        header.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        header.setText("Change Status");

        employeeLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        employeeLabel.setText("Employee :");

        userNameLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        userNameLabel.setText("Username :");

        employeeField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        employeeField.setText("Don Justine Fontanilla");

        userNameField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        userNameField.setText("Don Justine Fontanilla");

        currentStatus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        currentStatus.setText("Current Status :");

        cancelBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        resetBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        resetBtn.setText("Confirm");
        resetBtn.addActionListener(this::resetBtnActionPerformed);

        decorLine.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout decorLineLayout = new javax.swing.GroupLayout(decorLine);
        decorLine.setLayout(decorLineLayout);
        decorLineLayout.setHorizontalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        decorLineLayout.setVerticalGroup(
            decorLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        currentStatusLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        currentStatusLabel.setText("ACTIVE");

        changeToStatus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        changeToStatus.setText("Change to :");

        changeToLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        changeToLabel.setText("INACTIVE");

        javax.swing.GroupLayout resestPasswordPanelLayout = new javax.swing.GroupLayout(resestPasswordPanel);
        resestPasswordPanel.setLayout(resestPasswordPanelLayout);
        resestPasswordPanelLayout.setHorizontalGroup(
            resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header)
                    .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                    .addComponent(employeeLabel)
                                    .addGap(14, 14, 14)
                                    .addComponent(employeeField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                                .addComponent(decorLine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                    .addComponent(userNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                    .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentStatus)
                                        .addComponent(changeToStatus))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(changeToLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(currentStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        resestPasswordPanelLayout.setVerticalGroup(
            resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resestPasswordPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(header)
                .addGap(12, 12, 12)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeLabel)
                    .addComponent(employeeField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField))
                .addGap(12, 12, 12)
                .addComponent(decorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentStatus)
                    .addComponent(currentStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeToStatus)
                    .addComponent(changeToLabel))
                .addGap(24, 24, 24)
                .addGroup(resestPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resestPasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resestPasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        parentDialog.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        
        handleStatusChange();
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void successBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_successBtnActionPerformed
        // TODO add your handling code here:
        successDialog.dispose();
    }//GEN-LAST:event_successBtnActionPerformed

    private void errorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorBtnActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
    }//GEN-LAST:event_errorBtnActionPerformed

    private char defaultEcho;
    private AppContext appContext;
    private UserAccount selectedUser;
    private javax.swing.JDialog parentDialog;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel changeToLabel;
    private javax.swing.JLabel changeToStatus;
    private javax.swing.JLabel currentStatus;
    private javax.swing.JLabel currentStatusLabel;
    private javax.swing.JPanel decorLine;
    private javax.swing.JLabel employeeField;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JButton errorBtn;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JLabel header;
    private javax.swing.JPanel resestPasswordPanel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton successBtn;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel successPanel;
    private javax.swing.JLabel userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
