/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels.tools.reportviewermodal;

import com.motorph.payrollsystem.model.report.PayrollReport;
import com.motorph.payrollsystem.model.report.PayrollReportInfo;
import com.motorph.payrollsystem.model.report.PayrollReportRow;
import com.motorph.payrollsystem.utility.Dates;
import com.motorph.payrollsystem.utility.Money;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author djjus
 */
public class MainReportViewer extends javax.swing.JPanel {

    /**
     * Creates new form MainReportViewer
     */
    public MainReportViewer(
            PayrollReport report,
            javax.swing.JDialog dialog
    ) {
        this.report = report;
        this.parentDialog = dialog;
        
        loadPreviewIcon();
        initComponents();

        loadTableRow();
        loadOtherDetails();
        
    }
    
    private void loadPreviewIcon(){
        ImageIcon newIcon = new ImageIcon(getClass().getResource("/images/tab-icon/motorPhIcon.png"));
        
        Image img = newIcon.getImage();
        Image scaledImg = img.getScaledInstance(130, 94, Image.SCALE_SMOOTH);
        
        this.iconImage = new ImageIcon(scaledImg);
    }
    
    private void loadTableRow() {
        rowPanel.removeAll();
        
        for (PayrollReportRow row : report.getRows()) {
            rowPanel.add(new ReportRow(row));
            
        }
        
        
        rowPanel.revalidate();
        rowPanel.repaint();
    }
    
    private void loadOtherDetails() {
        PayrollReportInfo info = report.getReportInfo();
        
        //header
        start.setText(Dates.fullDate(info.getPayrollPeriod().getStartDate()));
        end.setText(Dates.fullDate(info.getPayrollPeriod().getEndDate()));
        generatedBy.setText(info.getGeneratedByName());
        generatedAt.setText(Dates.fullDateAndTime(info.getGeneratedAt()));
        empCount.setText(String.valueOf(info.getEmployeeCount()));
        
        //TOTALS
        grossTotal.setText(Money.displayMoney(info.getTotalGrossPay()));
        deductionsTotal.setText(Money.displayMoney(info.getTotalDeductions()));
        netTotal.setText(Money.displayMoney(info.getTotalNetPay()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printDialog = new javax.swing.JDialog(this.parentDialog, true);
        bgPanel = new javax.swing.JPanel();
        printNote = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        viewerPanel = new javax.swing.JPanel();
        viewerLabel = new javax.swing.JLabel();
        viewerPane = new javax.swing.JScrollPane();
        printArea = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        companyTitle = new javax.swing.JLabel();
        addrLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        monthlyLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        tableHeader = new javax.swing.JPanel();
        empNoLabel = new javax.swing.JLabel();
        empNameLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        hourlyRateLabel = new javax.swing.JLabel();
        totalHoursLabel = new javax.swing.JLabel();
        grossLabel = new javax.swing.JLabel();
        sssLabel = new javax.swing.JLabel();
        philHealthLabel = new javax.swing.JLabel();
        pagIbigLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        deductionsLabel = new javax.swing.JLabel();
        netLabel = new javax.swing.JLabel();
        rowPanel = new javax.swing.JPanel();
        periodStart = new javax.swing.JLabel();
        generatebByName = new javax.swing.JLabel();
        periodEnd = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        generatebByName1 = new javax.swing.JLabel();
        generatedBy = new javax.swing.JLabel();
        generatedAt = new javax.swing.JLabel();
        tableHeader1 = new javax.swing.JPanel();
        empNoLabel1 = new javax.swing.JLabel();
        empNameLabel1 = new javax.swing.JLabel();
        positionLabel1 = new javax.swing.JLabel();
        hourlyRateLabel1 = new javax.swing.JLabel();
        totalHoursLabel1 = new javax.swing.JLabel();
        grossTotal = new javax.swing.JLabel();
        sssTotal = new javax.swing.JLabel();
        philhealthTotal = new javax.swing.JLabel();
        pagibigTotal = new javax.swing.JLabel();
        taxTotal = new javax.swing.JLabel();
        deductionsTotal = new javax.swing.JLabel();
        netTotal = new javax.swing.JLabel();
        employeLabel = new javax.swing.JLabel();
        empCount = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();

        printDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        printDialog.setAlwaysOnTop(true);
        printDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        printDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        printDialog.setName("printingDialog"); // NOI18N
        printDialog.setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));

        printNote.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        printNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printNote.setText("This element is for printing simulation only");

        closeBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(this::closeBtnActionPerformed);

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(printNote, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(printNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout printDialogLayout = new javax.swing.GroupLayout(printDialog.getContentPane());
        printDialog.getContentPane().setLayout(printDialogLayout);
        printDialogLayout.setHorizontalGroup(
            printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printDialogLayout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        printDialogLayout.setVerticalGroup(
            printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        viewerPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewerLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        viewerLabel.setText("Payroll Report ");

        printArea.setBackground(new java.awt.Color(255, 255, 255));

        icon.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        icon.setIcon(this.iconImage);

        companyTitle.setFont(new java.awt.Font("Poppins", 3, 24)); // NOI18N
        companyTitle.setForeground(new java.awt.Color(0, 51, 102));
        companyTitle.setText("MotorPH");

        addrLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        addrLabel.setForeground(new java.awt.Color(0, 51, 102));
        addrLabel.setText("7 Jupiter Avenue cor. F. Sandoval");

        phoneLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(0, 51, 102));
        phoneLabel.setText("|     Phone: (028) 911-5071 / (028) 911-5072 / (028) 911-5073");

        monthlyLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        monthlyLabel.setForeground(new java.awt.Color(0, 51, 102));
        monthlyLabel.setText("MONTHLY PAYROLL SUMMARY REPORT");

        emailLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 51, 102));
        emailLabel.setText("|     Email: corporate@motorph.com");

        tableHeader.setBackground(new java.awt.Color(0, 51, 102));

        empNoLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        empNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        empNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empNoLabel.setText("Employee No");

        empNameLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        empNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        empNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empNameLabel.setText("Employee Name");

        positionLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(255, 255, 255));
        positionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionLabel.setText("Position");

        hourlyRateLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        hourlyRateLabel.setForeground(new java.awt.Color(255, 255, 255));
        hourlyRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourlyRateLabel.setText("Hourly Rate");

        totalHoursLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        totalHoursLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalHoursLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalHoursLabel.setText("Total Hours");

        grossLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        grossLabel.setForeground(new java.awt.Color(255, 255, 255));
        grossLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grossLabel.setText("Gross Pay");

        sssLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        sssLabel.setForeground(new java.awt.Color(255, 255, 255));
        sssLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sssLabel.setText("SSS");

        philHealthLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        philHealthLabel.setForeground(new java.awt.Color(255, 255, 255));
        philHealthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        philHealthLabel.setText("PhilHealth");

        pagIbigLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        pagIbigLabel.setForeground(new java.awt.Color(255, 255, 255));
        pagIbigLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagIbigLabel.setText("Pag-IBIG");

        taxLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(255, 255, 255));
        taxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taxLabel.setText("Withholding Tax");

        deductionsLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        deductionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        deductionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deductionsLabel.setText("Total Deductions");

        netLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        netLabel.setForeground(new java.awt.Color(255, 255, 255));
        netLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        netLabel.setText("Net Pay");

        javax.swing.GroupLayout tableHeaderLayout = new javax.swing.GroupLayout(tableHeader);
        tableHeader.setLayout(tableHeaderLayout);
        tableHeaderLayout.setHorizontalGroup(
            tableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(empNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grossLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sssLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(philHealthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagIbigLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deductionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableHeaderLayout.setVerticalGroup(
            tableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableHeaderLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(tableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNoLabel)
                    .addComponent(empNameLabel)
                    .addComponent(positionLabel)
                    .addComponent(hourlyRateLabel)
                    .addComponent(totalHoursLabel)
                    .addComponent(grossLabel)
                    .addComponent(sssLabel)
                    .addComponent(philHealthLabel)
                    .addComponent(pagIbigLabel)
                    .addComponent(taxLabel)
                    .addComponent(deductionsLabel)
                    .addComponent(netLabel))
                .addContainerGap())
        );

        rowPanel.setBackground(new java.awt.Color(153, 153, 153));
        rowPanel.setLayout(new javax.swing.BoxLayout(rowPanel, javax.swing.BoxLayout.Y_AXIS));

        periodStart.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        periodStart.setForeground(new java.awt.Color(0, 51, 102));
        periodStart.setText("Period Start :");

        generatebByName.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        generatebByName.setForeground(new java.awt.Color(0, 51, 102));
        generatebByName.setText("Generated by :");

        periodEnd.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        periodEnd.setForeground(new java.awt.Color(0, 51, 102));
        periodEnd.setText("Period End :");

        start.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        start.setForeground(new java.awt.Color(0, 51, 102));
        start.setText("March 1, 2026");

        end.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        end.setForeground(new java.awt.Color(0, 51, 102));
        end.setText("March 1, 2026");

        generatebByName1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        generatebByName1.setForeground(new java.awt.Color(0, 51, 102));
        generatebByName1.setText("Generated at :");

        generatedBy.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        generatedBy.setForeground(new java.awt.Color(0, 51, 102));
        generatedBy.setText("Alvaro R.");

        generatedAt.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        generatedAt.setForeground(new java.awt.Color(0, 51, 102));
        generatedAt.setText("May 5, 2026");

        tableHeader1.setBackground(new java.awt.Color(0, 51, 102));

        empNoLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        empNoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        empNoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empNoLabel1.setText("      ");

        empNameLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        empNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        empNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empNameLabel1.setText("    ");

        positionLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        positionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        positionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionLabel1.setText("      ");

        hourlyRateLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        hourlyRateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        hourlyRateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourlyRateLabel1.setText("    ");

        totalHoursLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        totalHoursLabel1.setForeground(new java.awt.Color(255, 255, 255));
        totalHoursLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalHoursLabel1.setText("TOTAL");

        grossTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        grossTotal.setForeground(new java.awt.Color(255, 255, 255));
        grossTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grossTotal.setText("Gross Pay");

        sssTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        sssTotal.setForeground(new java.awt.Color(255, 255, 255));
        sssTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sssTotal.setText("      ");

        philhealthTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        philhealthTotal.setForeground(new java.awt.Color(255, 255, 255));
        philhealthTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        philhealthTotal.setText("   ");

        pagibigTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        pagibigTotal.setForeground(new java.awt.Color(255, 255, 255));
        pagibigTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pagibigTotal.setText("   ");

        taxTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        taxTotal.setForeground(new java.awt.Color(255, 255, 255));
        taxTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taxTotal.setText("    ");

        deductionsTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        deductionsTotal.setForeground(new java.awt.Color(255, 255, 255));
        deductionsTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deductionsTotal.setText("Total Deductions");

        netTotal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        netTotal.setForeground(new java.awt.Color(255, 255, 255));
        netTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotal.setText("Net Pay");

        javax.swing.GroupLayout tableHeader1Layout = new javax.swing.GroupLayout(tableHeader1);
        tableHeader1.setLayout(tableHeader1Layout);
        tableHeader1Layout.setHorizontalGroup(
            tableHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(empNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyRateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalHoursLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grossTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sssTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(philhealthTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagibigTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deductionsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableHeader1Layout.setVerticalGroup(
            tableHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableHeader1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(tableHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNoLabel1)
                    .addComponent(empNameLabel1)
                    .addComponent(positionLabel1)
                    .addComponent(hourlyRateLabel1)
                    .addComponent(totalHoursLabel1)
                    .addComponent(grossTotal)
                    .addComponent(sssTotal)
                    .addComponent(philhealthTotal)
                    .addComponent(pagibigTotal)
                    .addComponent(taxTotal)
                    .addComponent(deductionsTotal)
                    .addComponent(netTotal))
                .addGap(6, 6, 6))
        );

        employeLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        employeLabel.setForeground(new java.awt.Color(0, 51, 102));
        employeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeLabel.setText("Employee Count: ");

        empCount.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        empCount.setForeground(new java.awt.Color(0, 51, 102));
        empCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        empCount.setText("34");

        javax.swing.GroupLayout printAreaLayout = new javax.swing.GroupLayout(printArea);
        printArea.setLayout(printAreaLayout);
        printAreaLayout.setHorizontalGroup(
            printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printAreaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printAreaLayout.createSequentialGroup()
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(printAreaLayout.createSequentialGroup()
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(companyTitle)
                                    .addGroup(printAreaLayout.createSequentialGroup()
                                        .addComponent(addrLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(phoneLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailLabel)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(printAreaLayout.createSequentialGroup()
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periodStart)
                                    .addComponent(periodEnd))
                                .addGap(24, 24, 24)
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generatebByName)
                                    .addComponent(generatebByName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printAreaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, printAreaLayout.createSequentialGroup()
                                .addComponent(monthlyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tableHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rowPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableHeader1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        printAreaLayout.setVerticalGroup(
            printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printAreaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(printAreaLayout.createSequentialGroup()
                        .addComponent(companyTitle)
                        .addGap(0, 0, 0)
                        .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addrLabel)
                            .addComponent(phoneLabel)
                            .addComponent(emailLabel))
                        .addGap(12, 12, 12)
                        .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(printAreaLayout.createSequentialGroup()
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(periodStart)
                                    .addComponent(start))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(periodEnd)
                                    .addComponent(end)))
                            .addGroup(printAreaLayout.createSequentialGroup()
                                .addComponent(generatebByName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatebByName1))
                            .addGroup(printAreaLayout.createSequentialGroup()
                                .addComponent(generatedBy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatedAt)))))
                .addGap(12, 12, 12)
                .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(monthlyLabel)
                    .addGroup(printAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empCount)
                        .addComponent(employeLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        viewerPane.setViewportView(printArea);

        printBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        printBtn.setText("PRINT");
        printBtn.addActionListener(this::printBtnActionPerformed);

        javax.swing.GroupLayout viewerPanelLayout = new javax.swing.GroupLayout(viewerPanel);
        viewerPanel.setLayout(viewerPanelLayout);
        viewerPanelLayout.setHorizontalGroup(
            viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewerPanelLayout.createSequentialGroup()
                        .addComponent(viewerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        viewerPanelLayout.setVerticalGroup(
            viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewerLabel)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(viewerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        printDialog.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        printDialog.setTitle("Printing...");
        printDialog.pack();
        printDialog.setResizable(false);
        printDialog.setLocationRelativeTo(null);
        
        printDialog.setVisible(true);
        
    }//GEN-LAST:event_printBtnActionPerformed

    private PayrollReport report;
    private ImageIcon iconImage;
    private javax.swing.JDialog parentDialog;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrLabel;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel companyTitle;
    private javax.swing.JLabel deductionsLabel;
    private javax.swing.JLabel deductionsTotal;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel empCount;
    private javax.swing.JLabel empNameLabel;
    private javax.swing.JLabel empNameLabel1;
    private javax.swing.JLabel empNoLabel;
    private javax.swing.JLabel empNoLabel1;
    private javax.swing.JLabel employeLabel;
    private javax.swing.JLabel end;
    private javax.swing.JLabel generatebByName;
    private javax.swing.JLabel generatebByName1;
    private javax.swing.JLabel generatedAt;
    private javax.swing.JLabel generatedBy;
    private javax.swing.JLabel grossLabel;
    private javax.swing.JLabel grossTotal;
    private javax.swing.JLabel hourlyRateLabel;
    private javax.swing.JLabel hourlyRateLabel1;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel monthlyLabel;
    private javax.swing.JLabel netLabel;
    private javax.swing.JLabel netTotal;
    private javax.swing.JLabel pagIbigLabel;
    private javax.swing.JLabel pagibigTotal;
    private javax.swing.JLabel periodEnd;
    private javax.swing.JLabel periodStart;
    private javax.swing.JLabel philHealthLabel;
    private javax.swing.JLabel philhealthTotal;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel positionLabel1;
    private javax.swing.JPanel printArea;
    private javax.swing.JButton printBtn;
    private javax.swing.JDialog printDialog;
    private javax.swing.JLabel printNote;
    private javax.swing.JPanel rowPanel;
    private javax.swing.JLabel sssLabel;
    private javax.swing.JLabel sssTotal;
    private javax.swing.JLabel start;
    private javax.swing.JPanel tableHeader;
    private javax.swing.JPanel tableHeader1;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel taxTotal;
    private javax.swing.JLabel totalHoursLabel;
    private javax.swing.JLabel totalHoursLabel1;
    private javax.swing.JLabel viewerLabel;
    private javax.swing.JScrollPane viewerPane;
    private javax.swing.JPanel viewerPanel;
    // End of variables declaration//GEN-END:variables
}
