/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.motorph.payrollsystem.gui.managementpanels.tools.reportviewermodal;

import com.motorph.payrollsystem.model.report.PayrollReportRow;
import com.motorph.payrollsystem.utility.Money;

/**
 *
 * @author djjus
 */
public class ReportRow extends javax.swing.JPanel {

    /**
     * Creates new form ReportRow
     */
    public ReportRow(
            PayrollReportRow row
    ) {
        this.row = row;
        
        
        initComponents();
        loadDetails();
        
    }
    
    private void loadDetails() {
        empNo.setText(row.getEmployeeNo());
        empName.setText(row.getEmployeeName());
        position.setText(row.getPosition());
        hourlyRate.setText(Money.displayMoney(row.getHourlyRate()));
        totalHours.setText(Money.displayMoney(row.getTotalHoursWorked()));
        gross.setText(Money.displayMoney(row.getGrossPay()));
        sss.setText(Money.displayMoney(row.getSssDeduction()));
        philHealth.setText(Money.displayMoney(row.getPhilHealthDeduction()));
        pagIbig.setText(Money.displayMoney(row.getPagIbigDeduction()));
        tax.setText(Money.displayMoney(row.getWithholdingTax()));
        deductions.setText(Money.displayMoney(row.getTotalDeductions()));
        net.setText(Money.displayMoney(row.getNetPay()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableHeader = new javax.swing.JPanel();
        empNo = new javax.swing.JLabel();
        empName = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        hourlyRate = new javax.swing.JLabel();
        totalHours = new javax.swing.JLabel();
        gross = new javax.swing.JLabel();
        sss = new javax.swing.JLabel();
        philHealth = new javax.swing.JLabel();
        pagIbig = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        deductions = new javax.swing.JLabel();
        net = new javax.swing.JLabel();

        tableHeader.setBackground(new java.awt.Color(255, 255, 255));

        empNo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        empNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empNo.setText("Employee No");

        empName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        empName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empName.setText("Employee Name");

        position.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        position.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        position.setText("Position");

        hourlyRate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        hourlyRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hourlyRate.setText("Hourly Rate");

        totalHours.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        totalHours.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalHours.setText("Total Hours");

        gross.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        gross.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gross.setText("Gross Pay");

        sss.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        sss.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sss.setText("SSS");

        philHealth.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        philHealth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        philHealth.setText("PhilHealth");

        pagIbig.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        pagIbig.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pagIbig.setText("Pag-IBIG");

        tax.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tax.setText("Withholding Tax");

        deductions.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        deductions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deductions.setText("Total Deductions");

        net.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        net.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        net.setText("Net Pay");

        javax.swing.GroupLayout tableHeaderLayout = new javax.swing.GroupLayout(tableHeader);
        tableHeader.setLayout(tableHeaderLayout);
        tableHeaderLayout.setHorizontalGroup(
            tableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empNo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalHours, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gross, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(philHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deductions, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(net, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableHeaderLayout.setVerticalGroup(
            tableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableHeaderLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(tableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNo)
                    .addComponent(empName)
                    .addComponent(position)
                    .addComponent(hourlyRate)
                    .addComponent(totalHours)
                    .addComponent(gross)
                    .addComponent(sss)
                    .addComponent(philHealth)
                    .addComponent(pagIbig)
                    .addComponent(tax)
                    .addComponent(deductions)
                    .addComponent(net))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private PayrollReportRow row;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deductions;
    private javax.swing.JLabel empName;
    private javax.swing.JLabel empNo;
    private javax.swing.JLabel gross;
    private javax.swing.JLabel hourlyRate;
    private javax.swing.JLabel net;
    private javax.swing.JLabel pagIbig;
    private javax.swing.JLabel philHealth;
    private javax.swing.JLabel position;
    private javax.swing.JLabel sss;
    private javax.swing.JPanel tableHeader;
    private javax.swing.JLabel tax;
    private javax.swing.JLabel totalHours;
    // End of variables declaration//GEN-END:variables
}
