/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.payrollsystem.GUI;

import com.motorph.payrollsystem.GUI.rightsidepanels.EmployeeInfoPanel;
import com.motorph.payrollsystem.GUI.rightsidepanels.HomePanel;
import com.motorph.payrollsystem.GUI.rightsidepanels.SalaryPanel;
import com.motorph.payrollsystem.GUI.rightsidepanels.LeavePanel;
import com.motorph.payrollsystem.app.AppContext;
import javax.swing.ImageIcon;




/**
 *
 * @author djjus
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    /**
     * Creates new form MainFrame
     * @param appContext the current logged in user/employee
     *
     */
    
    
    public MainFrame(AppContext appContext) {
        this.appContext = appContext;
        initComponents();
        setSize(1000, 640);
        setResizable(false);
        setLocationRelativeTo(null);
        
        //Righ panel default screen after logging in
        rightPanel.setLayout(new java.awt.BorderLayout());
        homeScreenDefault(appContext);
        
        
        //frame icon
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/images/tab-icon/motorPhFrame.png")
        );
        
        setIconImage(icon.getImage());
        setTitle("MotorPH Payroll - Employee");
 
    }
    
    private void changeRightScreen(javax.swing.JPanel panel) {
        rightPanel.removeAll();
        rightPanel.add(panel, java.awt.BorderLayout.CENTER);
        rightPanel.revalidate();
        rightPanel.repaint();
    }
    
    private void btnMouseEntered(javax.swing.JPanel panel) {
        panel.setBackground(new java.awt.Color(240, 240, 240));
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    
    private void btnMouseExited(javax.swing.JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }
    
    private void homeScreenDefault(AppContext context) {
        changeRightScreen(new HomePanel(context));
    }
    
    private void logoutDialog() {
        logoutConfirm.setSize(340, 176);
        logoutConfirm.setResizable(false);
        logoutConfirm.setLocationRelativeTo(this);
        logoutConfirm.setTitle("Logging out...");
        
        logoutConfirm.setVisible(true);
 
    }
    
    private void logoutClosing() {
        this.logoutConfirm.dispose();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutConfirm = new javax.swing.JDialog();
        logoutMessage = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        yesBtn = new javax.swing.JButton();
        leftSidePanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        homeBtn = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        profileBtn = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        salaryBtn = new javax.swing.JPanel();
        salaryLabel = new javax.swing.JLabel();
        leaveBtn = new javax.swing.JPanel();
        leaveLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();

        logoutConfirm.setAlwaysOnTop(true);
        logoutConfirm.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        logoutConfirm.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                logoutConfirmWindowClosing(evt);
            }
        });

        logoutMessage.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        logoutMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutMessage.setText("Are you sure you want to log out ?");

        cancelBtn.setBackground(new java.awt.Color(255, 204, 204));
        cancelBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        yesBtn.setBackground(new java.awt.Color(204, 255, 204));
        yesBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        yesBtn.setText("Yes");
        yesBtn.addActionListener(this::yesBtnActionPerformed);

        javax.swing.GroupLayout logoutConfirmLayout = new javax.swing.GroupLayout(logoutConfirm.getContentPane());
        logoutConfirm.getContentPane().setLayout(logoutConfirmLayout);
        logoutConfirmLayout.setHorizontalGroup(
            logoutConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutConfirmLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cancelBtn)
                .addGap(75, 75, 75)
                .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(logoutMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoutConfirmLayout.setVerticalGroup(
            logoutConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutConfirmLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(logoutMessage)
                .addGap(18, 18, 18)
                .addGroup(logoutConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(yesBtn))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setResizable(false);

        leftSidePanel.setBackground(new java.awt.Color(255, 255, 255));
        leftSidePanel.setToolTipText("");
        leftSidePanel.setPreferredSize(new java.awt.Dimension(240, 640));

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setText("LOG OUT");
        logoutLabel.setMaximumSize(new java.awt.Dimension(56, 22));
        logoutLabel.setMinimumSize(new java.awt.Dimension(56, 22));
        logoutLabel.setNextFocusableComponent(homeBtn);
        logoutLabel.setPreferredSize(new java.awt.Dimension(56, 22));

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        navBar.setBackground(new java.awt.Color(255, 255, 255));
        navBar.setPreferredSize(new java.awt.Dimension(195, 380));

        homeBtn.setBackground(new java.awt.Color(255, 255, 255));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("HOME");
        homeLabel.setNextFocusableComponent(homeBtn);
        homeLabel.setPreferredSize(new java.awt.Dimension(56, 22));

        javax.swing.GroupLayout homeBtnLayout = new javax.swing.GroupLayout(homeBtn);
        homeBtn.setLayout(homeBtnLayout);
        homeBtnLayout.setHorizontalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeBtnLayout.setVerticalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        profileBtn.setBackground(new java.awt.Color(255, 255, 255));
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnMouseExited(evt);
            }
        });

        profileLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel.setText("PROFILE");
        profileLabel.setNextFocusableComponent(homeBtn);

        javax.swing.GroupLayout profileBtnLayout = new javax.swing.GroupLayout(profileBtn);
        profileBtn.setLayout(profileBtnLayout);
        profileBtnLayout.setHorizontalGroup(
            profileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        profileBtnLayout.setVerticalGroup(
            profileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        salaryBtn.setBackground(new java.awt.Color(255, 255, 255));
        salaryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salaryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salaryBtnMouseExited(evt);
            }
        });

        salaryLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        salaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaryLabel.setText("SALARY");
        salaryLabel.setMaximumSize(new java.awt.Dimension(56, 22));
        salaryLabel.setMinimumSize(new java.awt.Dimension(56, 22));
        salaryLabel.setNextFocusableComponent(homeBtn);
        salaryLabel.setPreferredSize(new java.awt.Dimension(56, 22));

        javax.swing.GroupLayout salaryBtnLayout = new javax.swing.GroupLayout(salaryBtn);
        salaryBtn.setLayout(salaryBtnLayout);
        salaryBtnLayout.setHorizontalGroup(
            salaryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        salaryBtnLayout.setVerticalGroup(
            salaryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryBtnLayout.createSequentialGroup()
                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        leaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        leaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leaveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leaveBtnMouseExited(evt);
            }
        });

        leaveLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        leaveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaveLabel.setText("LEAVE");
        leaveLabel.setMaximumSize(new java.awt.Dimension(56, 22));
        leaveLabel.setMinimumSize(new java.awt.Dimension(56, 22));
        leaveLabel.setNextFocusableComponent(homeBtn);
        leaveLabel.setPreferredSize(new java.awt.Dimension(56, 22));

        javax.swing.GroupLayout leaveBtnLayout = new javax.swing.GroupLayout(leaveBtn);
        leaveBtn.setLayout(leaveBtnLayout);
        leaveBtnLayout.setHorizontalGroup(
            leaveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(leaveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(leaveLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        leaveBtnLayout.setVerticalGroup(
            leaveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(leaveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(leaveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salaryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        rightPanel.setPreferredSize(new java.awt.Dimension(760, 640));
        rightPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        // TODO add your handling code here:
        homeScreenDefault(this.appContext);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void rightPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rightPanelMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        // TODO add your handling code here:
        changeRightScreen(new EmployeeInfoPanel(this.appContext));
    }//GEN-LAST:event_profileBtnMouseClicked

    private void salaryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryBtnMouseClicked
        // TODO add your handling code here:
        changeRightScreen(new SalaryPanel(this.appContext));
    }//GEN-LAST:event_salaryBtnMouseClicked

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(homeBtn);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        // TODO add your handling code here:
        btnMouseExited(homeBtn);
    }//GEN-LAST:event_homeBtnMouseExited

    private void profileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(profileBtn);
    }//GEN-LAST:event_profileBtnMouseEntered

    private void profileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseExited
        // TODO add your handling code here:
        btnMouseExited(profileBtn);
    }//GEN-LAST:event_profileBtnMouseExited

    private void leaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveBtnMouseClicked
        // TODO add your handling code here:
        changeRightScreen(new LeavePanel(this.appContext));
    }//GEN-LAST:event_leaveBtnMouseClicked

    private void salaryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryBtnMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(salaryBtn);
    }//GEN-LAST:event_salaryBtnMouseEntered

    private void salaryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryBtnMouseExited
        // TODO add your handling code here:
        btnMouseExited(salaryBtn);
    }//GEN-LAST:event_salaryBtnMouseExited

    private void leaveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveBtnMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(leaveBtn);
    }//GEN-LAST:event_leaveBtnMouseEntered

    private void leaveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveBtnMouseExited
        // TODO add your handling code here:
        btnMouseExited(leaveBtn);
    }//GEN-LAST:event_leaveBtnMouseExited

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        logoutDialog();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(logoutBtn);
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        // TODO add your handling code here:
        btnMouseExited(logoutBtn);
    }//GEN-LAST:event_logoutBtnMouseExited

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        logoutClosing();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        // TODO add your handling code here:
        this.logoutConfirm.dispose();
        this.appContext.getSessionManager().endSession();
        PasswordFrame loginFrame = new PasswordFrame(appContext);
        loginFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_yesBtnActionPerformed

    private void logoutConfirmWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_logoutConfirmWindowClosing
        // TODO add your handling code here:
        logoutClosing();
    }//GEN-LAST:event_logoutConfirmWindowClosing
    

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MainFrame(this.appContext).setVisible(true));
    }
    

    private final AppContext appContext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel leaveBtn;
    private javax.swing.JLabel leaveLabel;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JDialog logoutConfirm;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel logoutMessage;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel profileBtn;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel salaryBtn;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
