/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.payrollsystem.GUI;

import com.motorph.payrollsystem.app.AppContext;

import com.motorph.payrollsystem.domain.auth.UserAccount;
import com.motorph.payrollsystem.domain.employee.Employee;
import com.motorph.payrollsystem.service.AuthService;
import javax.swing.ImageIcon;

/**
 *
 * @author djjus
 */
public class PasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public PasswordFrame(AppContext appContext) {
        this.appContext = appContext;
        initComponents();
        setSize(418, 500);
        setResizable(false);
        setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/images/keyIcon.png")
        );
        
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customDialog = new javax.swing.JDialog();
        customDialogLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        passwordPanel = new javax.swing.JPanel();
        employeeLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        empNoTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        customDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        customDialog.setBackground(new java.awt.Color(255, 255, 255));
        customDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        customDialog.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        customDialogLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        customDialogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customDialogLabel.setText("template");

        okBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customDialogLayout = new javax.swing.GroupLayout(customDialog.getContentPane());
        customDialog.getContentPane().setLayout(customDialogLayout);
        customDialogLayout.setHorizontalGroup(
            customDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customDialogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(customDialogLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        customDialogLayout.setVerticalGroup(
            customDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(customDialogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okBtn)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(440, 400));
        setResizable(false);

        passwordPanel.setBackground(new java.awt.Color(255, 255, 255));

        employeeLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        employeeLabel.setText("EMPLOYEE NO:");

        usernameLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        usernameLabel.setText("USERNAME :");

        passwordLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        passwordLabel.setText("PASSWORD:");

        loginBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPassword(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passwordLogoResized.jpg"))); // NOI18N

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passwordPanelLayout.createSequentialGroup()
                                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                                .addComponent(employeeLabel)
                                .addGap(18, 18, 18)))
                        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empNoTextField)
                            .addComponent(passwordField)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(passwordPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(10, 10, 10)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPassword(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPassword
        // TODO add your handling code here:
//        For easy testing the mainframe
//        MainFrame mainFrame = new MainFrame();
//        mainFrame.setVisible(true);
//        this.dispose();
        
        //trim to remove pre or post spaces
        String empNo = empNoTextField.getText().trim();
        String username = userNameTextField.getText().trim();
        String password = new String(passwordField.getPassword());
        
        if (empNo.isEmpty() || username.isEmpty() || password.isEmpty()) {
            customizeDialog("Missing Inputs", "All fields are required");
            return;
        }
        
        try {
            AuthService authService = appContext.getAuthService();
            UserAccount userAccount = authService.login(empNo, username, password);
            
            if (userAccount != null) {
                Employee currEmployee = appContext.getEmployeeService().findByEmployeeNo(userAccount.getEmployeeNo());
                appContext.getSessionManager().startSession(userAccount, currEmployee);
                
                MainFrame mainFrame = new MainFrame(appContext);
                mainFrame.setVisible(true);
                this.dispose();
            } else {
                customizeDialog("Login Failed", "Invalid Credentials");
                passwordField.setText("");
                passwordField.requestFocus();
            }
        } catch (Exception ex) {
            customizeDialog("Check Resource", "Invalid Path");
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_checkPassword
    
    private void customizeDialog(String title, String label) {
        customDialog.setSize(225, 160);
        customDialog.setResizable(false);
        customDialog.setLocationRelativeTo(null);
        customDialog.setTitle(title);
        
        customDialogLabel.setText(label);
        
        this.setEnabled(false);
        customDialog.setVisible(true);
        
    }
    
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        this.setEnabled(true);
        customDialog.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PasswordFrame(this.appContext).setVisible(true);
//            }
//        });
    }
    
    private javax.swing.JLabel imageLogo;
    private AppContext appContext;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog customDialog;
    private javax.swing.JLabel customDialogLabel;
    private javax.swing.JTextField empNoTextField;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
